DROP TABLE IF EXISTS property;

CREATE TABLE property(
  id VARCHAR (32) PRIMARY KEY,
  title VARCHAR (60) NOT NULL,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  body TEXT NOT NULL,
  amount FLOAT NOT NULL DEFAULT 0.0
)